// Single source of truth for firm identity / NAP (name, address, phone) — used
// by metadata, JSON-LD structured data, the footer, and contact affordances.

import type { Metadata } from "next";

export const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://www.patelaccounting.in";

export const FIRM = {
  name: "Patel Accounting & Legal Services",
  phone: "+919825442028",
  phoneDisplay: "98254 42028",
  altPhone: "+918980413939",
  email: "saurabhpateloffice2026@gmail.com",
  whatsapp: "919825442028",
  foundingDate: "2006",
  street: "4th Floor, Office No. 7, Vinod Chamber, Dariyapur Road, Dariyapur",
  locality: "Ahmedabad",
  region: "Gujarat",
  postalCode: "380001",
  country: "IN",
} as const;

// Per-page metadata for the static marketing pages. Next.js does NOT deep-merge
// a child's `openGraph`/`twitter` into the root's, nor derive og:title from a
// page's `title`, so a page that sets only title/description silently inherits
// the HOMEPAGE og:*/twitter:* values. This helper sets canonical + a complete,
// page-specific OpenGraph/Twitter block in one place so every page shares
// correct, non-stale social metadata. (og:image comes from app/opengraph-image.)
// Default share image, generated by app/opengraph-image.tsx. Referenced
// explicitly because Next replaces (never merges) a child `openGraph`, so the
// auto-injected file image is lost on any page that sets its own openGraph.
export const OG_IMAGE = "/opengraph-image";

export function pageMeta(title: string, description: string, path: string): Metadata {
  const full = `${title} · ${FIRM.name}`;
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      locale: "en_IN",
      siteName: FIRM.name,
      title: full,
      description,
      url: path,
      images: [{ url: OG_IMAGE, width: 1200, height: 630, alt: FIRM.name }],
    },
    twitter: { card: "summary_large_image", title: full, description, images: [OG_IMAGE] },
  };
}

// schema.org LocalBusiness (AccountingService subtype). Rendered once, sitewide,
// so the firm is eligible for local rich results — something almost no competitor
// in this market has.
export function localBusinessJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "AccountingService",
    "@id": `${SITE_URL}/#business`,
    name: FIRM.name,
    url: SITE_URL,
    telephone: FIRM.phone,
    email: FIRM.email,
    foundingDate: FIRM.foundingDate,
    priceRange: "₹₹",
    address: {
      "@type": "PostalAddress",
      streetAddress: FIRM.street,
      addressLocality: FIRM.locality,
      addressRegion: FIRM.region,
      postalCode: FIRM.postalCode,
      addressCountry: FIRM.country,
    },
    areaServed: { "@type": "City", name: "Ahmedabad" },
    openingHoursSpecification: [
      {
        "@type": "OpeningHoursSpecification",
        dayOfWeek: [
          "Monday",
          "Tuesday",
          "Wednesday",
          "Thursday",
          "Friday",
          "Saturday",
        ],
        opens: "10:00",
        closes: "19:00",
      },
    ],
  };
}
